#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# CI-specific doxygen script that downloads and uses doxygen 1.9.1

DOXYGEN_VERSION="1.9.1"
CONDA_ENV_NAME="doxygen_ci_${DOXYGEN_VERSION}"
CONDA_PREFIX="/tmp/miniconda3"

# Function to setup miniconda if not available
setup_conda() {
    if [ ! -f "${CONDA_PREFIX}/bin/conda" ]; then
        echo "Setting up miniconda for CI..."
        curl -L "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" -o "/tmp/miniconda.sh"
        if [ $? -ne 0 ]; then
            echo "Error: Failed to download miniconda"
            exit 1
        fi
        
        bash "/tmp/miniconda.sh" -b -p "${CONDA_PREFIX}"
        if [ $? -ne 0 ]; then
            echo "Error: Failed to install miniconda"
            exit 1
        fi
        
        rm -f "/tmp/miniconda.sh"
        echo "Miniconda installed successfully"
    fi
}

# Function to setup doxygen environment
setup_doxygen_env() {
    source "${CONDA_PREFIX}/etc/profile.d/conda.sh"
    
    # Check if environment already exists with correct doxygen version
    if conda env list | grep -q "${CONDA_ENV_NAME}"; then
        conda activate "${CONDA_ENV_NAME}"
        CURRENT_VERSION=$(doxygen --version 2>/dev/null || echo "none")
        if [ "${CURRENT_VERSION}" = "${DOXYGEN_VERSION}" ]; then
            echo "Using existing doxygen ${DOXYGEN_VERSION} CI environment"
            return 0
        else
            echo "Removing existing CI environment with incorrect version"
            conda deactivate 2>/dev/null || true
            conda env remove -n "${CONDA_ENV_NAME}" -y
        fi
    fi
    
    echo "Creating new doxygen ${DOXYGEN_VERSION} CI environment..."
    # Accept conda ToS and use only conda-forge channel
    conda config --set solver libmamba
    conda config --remove channels defaults --force 2>/dev/null || true
    conda config --add channels conda-forge
    conda create -n "${CONDA_ENV_NAME}" --override-channels -c conda-forge "doxygen=${DOXYGEN_VERSION}" -y
    if [ $? -ne 0 ]; then
        echo "Error: Failed to create conda environment with doxygen ${DOXYGEN_VERSION}"
        exit 1
    fi
    
    conda activate "${CONDA_ENV_NAME}"
    echo "Doxygen ${DOXYGEN_VERSION} CI environment created and activated"
}

# Setup conda and doxygen environment
setup_conda
setup_doxygen_env

# Verify doxygen version
ACTUAL_VERSION=$(doxygen --version)
echo "Using doxygen version: ${ACTUAL_VERSION}"

# Extract just the version number (ignore git hash suffix)
ACTUAL_VERSION_NUM=$(echo "${ACTUAL_VERSION}" | cut -d' ' -f1)
if [ "${ACTUAL_VERSION_NUM}" != "${DOXYGEN_VERSION}" ]; then
    echo "Error: Expected doxygen version ${DOXYGEN_VERSION}, but got ${ACTUAL_VERSION_NUM}"
    exit 1
fi

# Run doxygen, ignore missing tag files error
TAG_ERROR1="error: Tag file '.*.tag' does not exist or is not a file. Skipping it..."
TAG_ERROR2="error: cannot open tag file .*.tag for writing"
DOXYGEN_STDERR=`cd doxygen && { cat Doxyfile ; echo QUIET = YES; echo GENERATE_HTML = NO; }  | doxygen - 2>&1 | sed "/\($TAG_ERROR1\|$TAG_ERROR2\)/d"`
RETVAL=$?

if [ "$RETVAL" != "0" ] || [ ! -z "$DOXYGEN_STDERR" ]; then
  echo -e "\n>>>> FAILED: doxygen check; begin output\n"
  echo -e "$DOXYGEN_STDERR"
  echo -e "\n>>>> FAILED: doxygen check; end output\n"
  RETVAL=1 #because return value is not generated by doxygen 1.8.17
else
  echo -e "\n>>>> PASSED: doxygen check\n"
fi

exit $RETVAL 